services:
  - type: web
    name: frontend
    env: static
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SUPABASE_URL
        fromEnv: VITE_SUPABASE_URL
      - key: VITE_SUPABASE_ANON_KEY
        fromEnv: VITE_SUPABASE_ANON_KEY
      - key: VITE_API_URL
        fromEnv: VITE_API_URL
      - key: VITE_DEV_MODE
        value: false
      - key: VITE_SKIP_AUTH  
        value: false
