services:
  - type: web
    name: seren-path-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: DEBUG
        value: "false"  # 本番環境では false
      - key: FRONTEND_URL
        value: "https://hack1-anti-optimized-system.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11"
    # ヘルスチェック設定
    healthCheckPath: "/health"
    # リソース設定
    plan: starter  # 無料プラン
    # 環境設定
    runtime: python3.11