services:
  - type: web
    name: seren-path-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: GOOGLE_API_KEY
        sync: false      - key: DEBUG
        value: "true"  # CORS問題解決のため一時的にtrue      - key: FRONTEND_URL
        value: "https://srv-d10tcb6mcj7s73c25j7g.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11"
    # ヘルスチェック設定
    healthCheckPath: "/health"
    # リソース設定
    plan: starter  # 無料プラン
    # 環境設定
    runtime: python3.11